#!/usr/bin/env bash
# Install nginx on your web-01 listening on port 80
# returning a page that contains the string Hello World!

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo echo "Hello World!" > /var/www/html/default
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
