#!/usr/bin/env bash
# Installs nginx on a web server.
sudo apt-get -y update
sudo apt-get -y install nginx
string="Hello World!"
echo "server {
    listen 80;
    listen [::]:80;
    
    location / {
        return 200 '$string';
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx start
