#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# redirection must be a 301 Moved Permanently 

sudo echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=urT8Tl6y4Co;
        }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
