#!/usr/bin/env bash
# Installs nginx on a web server.
sudo apt-get -y update
sudo apt-get -y install nginx
Error="Ceci n'est pas une page"
echo "$Error" | sudo tee /var/www/html/custom_404.html
echo "server {
    listen 80;
    listen [::]:80;
    error_page 404 /custom_404.html;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=o_oenl2Be-w;
    }
    location /error404.html {
        root /var/www/html;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx start
