#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the correct configurations
sudo pt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get update
sudo apt-get install -y haproxy=2.7.\*

echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}

echo "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 169779-web-01 52.91.202.129:80 check
    server 169779-web-02 54.87.209.214:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy start
