#!/usr/bin/env bash
# Installs HAProxy version 2.7.9 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  hbnb
        bind *:80
        mode http
        default_backend hbnb
backend hbnb
        balance roundrobin
        server 169779-web-01 52.91.136.87 check
        server 169779-web-02 54.236.12.110 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start
