#!/usr/bin/env bash
# Debugged configuration

echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;
    server_name localhost;

    location / {
        try_files $uri $uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default

sudo service nginx start
