#!/usr/bin/env bash
# Shorter version of config file automation
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo sed -i "s/ipv6only=yes/ipv6only=no/g" /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
