#!/usr/bin/env bash
#Prints Best School ten times
i=1
while [ $i -le 10 ];
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	else
		if [ $i -eq 8 ]
		then
			echo "good luck"
		else
			echo "Best School"
		fi
	fi
	((i++));
done
