#!/usr/bin/env bash
# Prints numbers from 1 to 20 replacing 4, 9, and 17 with text
i=1
while [ $i -le 20 ];
do 
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
	esac
	((i++));
done
