#!/bin/bash
# enable ufw and update rules to allow only ssh, https, and http

sudo su
ufw default deny incoming
ufw default allow outgoing
ufw allow "Nginx HTTP"
ufw allow "Nginx HTTPS"
ufw allow "Nginx Full"
ufw allow ssh
ufw enable
